### ISSUE TITLE
about cocoapods and AFNetworking

### ISSUE THREAD

**Issue by sosng** [AFNetworking/AFOAuth1Client#114]
Hi~
  I add AFOAuth1Client and AFNetworking to my podfile, the cocoapods shows that AFOAuth1Client requires AFNetworking 1.3.4, so it installs AFNetworking 1.3.4 not the 2.0,  many new methods cannot use, hope you can fix this problem : ]

**Comment by mattt** [comment]
AFOAuth1Client is not compatible with AFNetworking 2.0. There are no current plans to add compatibility.
