### ISSUE TITLE
receiving oauth_tken and oauth_verifier but how to create new access token for method acquireAccess

### ISSUE THREAD

**Issue by chrisallick** [AFNetworking/AFOAuth1Client#16]
when i connect to tumblr i receive something like this back in my app:

oauth_token=rYLleqRDZiJiG2jZUWt3AMwtjAVZZobn5nZuyhtArDfaMkcT7R&oauth_verifier=DyWKUoxPwziMZfjwFg92mjJziU2F8LHawpE8c0LcMDh1Ta6Jjg

i am able to parse the params, but how do i create a new request to get access token?  the init with query string method throws and error because there is no secret in this string

**Comment by mattt** [comment]
Others have reported success with Tumblr after the latest pull requests have been merged into master. Try upgrading your version of `AFOAuth1Client`, and ensure that you're using `-authorizeUsingOAuthWithRequestTokenPath:userAuthorizationPath:callbackURL:accessTokenPath:accessMethod:success:failure:`, which should take care of all of that for you.
