### ISSUE TITLE
LinkedIn OAuth1.0a fails

### ISSUE THREAD

**Issue by pj4533** [AFNetworking/AFOAuth1Client#17]
Two problems:
- Content-Type needs to be text/xml.   Probably nothing to be done here, since this seems very LinkedIn-only-ish.
- "Properly handling oauth_token_secret" - Apparently 'Twitter is particularly lenient with the use of oauth_token_secret' (http://developer.linkedin.com/documents/common-issues-oauth-authentication).    Maybe this deserves a pull-request update in AFOAuth1Client?   

I made a subclass that works here:  https://github.com/pj4533/AFLinkedInOAuth1Client

Interested to hear your thoughts.  I'll make a pull request, if you think necessary.

**Comment by mattt** [comment]
I don't think there's anything to be done about the `text/xml` content type. That's an unfortunate quirk of LinkedIn's system.

With regards to the lenient oath_token_secret, feel free to send a pull request if that's something you think is necessary. I didn't see anything about that specifically in your extension, so I'm assuming that it's not a deal breaker.

As for the other aspects of what your subclass does, f285886 should obviate the need to override `-acquireOAuthAccessTokenWithPath:...` as you do. I'm not sure why that was the way it was.

**Comment by seivan** [comment]
So what's the state here? I can't use normal AFOAuth1Client to login with linked in. 
signature_invalid

**Comment by pj4533** [comment]
You can checkout my subclass:  https://github.com/pj4533/AFLinkedInOAuth1Client

Also, make sure to read this:   https://github.com/AFNetworking/AFOAuth1Client/issues/24

**Comment by seivan** [comment]
Yup, using your pod now, thanks a lot, appreciate it.

On Mar 19, 2013, at 10:45 PM, PJ Gray <notifications@github.com<mailto:notifications@github.com>> wrote:

You can checkout my subclass: https://github.com/pj4533/AFLinkedInOAuth1Client

Also, make sure to read this: #24https://github.com/AFNetworking/AFOAuth1Client/issues/24
