### ISSUE TITLE
Make expiration a public property?

### ISSUE THREAD

**Issue by iamcam** [AFNetworking/AFOAuth1Client#31]
I'm wondering if expiration should be a public property. This is coming up as I'm serializing the parameters so I can recreate my auth'd sessions when leaving and returning to the app, using this to reinstate my AFOAuth1Client:

``` objective-c
- (id)initWithKey:(NSString *)key
           secret:(NSString *)secret
          session:(NSString *)session
       expiration:(NSDate *)expiration
        renewable:(BOOL)canBeRenewed;
```

It's minor, but maybe there's a good reason it's not already.

**Comment by mattt** [comment]
Thanks to #37, `AFOAuth1Token` now conforms to `NSCoding`, which means that you won't need to serialize that yourself.
