### ISSUE TITLE
getSatisfaction API fails to authenticate

### ISSUE THREAD

**Issue by mserougi** [AFNetworking/AFOAuth1Client#32]
The authorization process fails in "authorizeUsingOAuthWithRequestTokenPath" although I can see an access token in the "kAFApplicationLaunchOptionsURLKey" value.

Here's a sample project:
http://cl.ly/2Y340z390u2a

Thoughts on what's wrong?

**Comment by mattt** [comment]
I'm sorry, but I wasn't able to reproduce this. Perhaps something got fixed since this was first opened?

**Comment by mserougi** [comment]
That's possible, thanks for trying to reproduce.
