### ISSUE TITLE
Wrong sort order for AFHMACSHA1Signature

### ISSUE THREAD

**Issue by touchbyte** [AFNetworking/AFOAuth1Client#36]
The OAuth RFC standard states in 3.4.1.3.2: 
1.  The parameters are sorted by name, using ascending byte value ordering.  If two or more parameters share the same name, they are sorted by their value.

AFHMACSHA1Signature sorts the parameters case insensitive which is not ascending byte value ordering. You should use case sensitve ordering instead:

``` objective-c
NSString *queryString = AFPercentEscapedQueryStringPairMemberFromStringWithEncoding([[[[[request URL] query] componentsSeparatedByString:@"&"] sortedArrayUsingSelector:@selector(compare:)] componentsJoinedByString:@"&"], stringEncoding);
```

If you for example use OAuth with the SmugMug photo service, most API functions work fine, but the smugmug.albums.create function is not working correctly with AFOAuth1Client because SmugMug uses a Title parameter for this API function. With the current release Title is sorted after all the oauth_... parameters but it must be prior to this parameters because the uppercase 'T' is prior to the lowercase 'o' in byte value ordering.
This leads to an invalid signature error in the SmugMug API request.

**Comment by mattt** [comment]
Good call. I attributed c8f53e8 as best I could to you, since this issue is effectively a small pull request. Cheers!
