### ISSUE TITLE
Nonce always the same?

### ISSUE THREAD

**Issue by kylebrowning** [AFNetworking/AFOAuth1Client#4]
Im not sure why, maybe I dont fully understand oauth but, the oauth_nonce is always the same for me. Shouldnt this just be a randomly generated string of characters usually something to do with the timestamp etc?

Attempting to authenticate against another oauth api besides twitter and I still generate the same nonce every time.

 oauth_nonce="cmVxdWVzdF90bw", 

Im using the simulator, should I be using a device instead?

**Comment by iamcam** [comment]
I just found this out as well. I tried getting the AFBase64EncodedStringFromString function to work, but I'm getting compile errors. I'm not familiar with using static functions, but it seems there's something wrong, as XCode is giving me compile errors. There are some fixes that seem to work in AFNetworking core, but I'm not sure I have the right approach.

**Comment by mattt** [comment]
Happy to report that nonces (as well as everything else) is working as expected as of version 0.1.0. Sorry for the delay!
