### ISSUE TITLE
Doesn't work with DotNetOpenAuth

### ISSUE THREAD

**Issue by nnhubbard** [AFNetworking/AFOAuth1Client#43]
I have a service that uses DotNetOpenAuth, but AFOAuth1Client won't work with it.

**Comment by mattt** [comment]
_cool_story_bro.gif_

But seriously, do you have any more details to help debug the problem?

**Comment by nnhubbard** [comment]
Yeah, I admit this is the lamest issue report ever. It was a late night. Will close and open when I can give appropriate evidences.
