### ISSUE TITLE
acquireOAuthRequestTokenWithPath: method should check for oauth_error_message string in response

### ISSUE THREAD

**Issue by nnhubbard** [AFNetworking/AFOAuth1Client#46]
An OAuth client I am using sends errors back within the success block of `acquireOAuthRequestTokenWithPath:...`. Should we just check for an occurrence of the `oauth_error_message` string then return an error if it is found?

**Comment by mattt** [comment]
With 84d3bb8fcfcadffbb31cb9eac4fb97c3a5c12bbf, `AFOAuth1Token` objects have a `userInfo` property, which captures any non-standard parameters sent by the server (such as `oauth_error_message`).
