### ISSUE TITLE
Failed to validate oauth signature and token

### ISSUE THREAD

**Issue by inravewetrust** [AFNetworking/AFOAuth1Client#47]
I've run your example, and this is what I've got.

Error: Error Domain=AFNetworkingErrorDomain Code=-1011 "Expected status code in (200-299), got 401" UserInfo=0x8945ef0 {NSLocalizedRecoverySuggestion=Failed to validate oauth signature and token, AFNetworkingOperationFailingURLRequestErrorKey=<NSMutableURLRequest https://api.twitter.com/oauth/request_token>, NSErrorFailingURLKey=https://api.twitter.com/oauth/request_token, NSLocalizedDescription=Expected status code in (200-299), got 401, AFNetworkingOperationFailingURLResponseErrorKey=<NSHTTPURLResponse: 0x71603d0>}

**Comment by subh007** [comment]
I am also receiving same message on running both the examples.
