### ISSUE TITLE
Problem with ~ symbol

### ISSUE THREAD

**Issue by cusquinho** [AFNetworking/AFOAuth1Client#48]
Hi,

First of all, great library, been working like a charm for me!

The only issue I get is with the ~ char, every other special character I've tried work just fine. For some reason if I have ~ in the content I'm posting, I get:Error Domain=AFNetworkingErrorDomain Code=-1011 , status code 400 - 40104:incorrect signature". I have tried to encode the '~' char with urlEncoding format, but still get the same error. I also noticed you have ~ removed from the encoding list on your code - but either by adding it back or not, it still gives the same. 

Any help?

Thanks,

**Comment by dlackty** [comment]
@cusquinho I believe it has been fixed in AFNetworking/AFNetworking@9d1e780.

**Comment by mattt** [comment]
@dlackty Indeed it has. A `pod update` should fix all of this.
