### ISSUE TITLE
To support multiple server endpoints fo steps of authorizing

### ISSUE THREAD

**Issue by pinxue** [AFNetworking/AFOAuth1Client#49]
For example, Dropbox use api.dropbox.com for request_token and access_token, but www.dropbox.com for authorize.

**Comment by pinxue** [comment]
My temporary solution is to patch AFHTTPClient.m

``` objective-c
- (NSMutableURLRequest *)requestWithMethod:(NSString *)method
                                      path:(NSString *)path
                                parameters:(NSDictionary *)parameters
{
...
    NSURL *url = nil;
    if ( [path rangeOfString:@"://"].location == NSNotFound ) {
        url = [NSURL URLWithString:path relativeToURL:self.baseURL];
    } else {
        url = [NSURL URLWithString:path];
    }
...    
}
```

**Comment by pinxue** [comment]
This temporary solution is fine for authorization step, it will cause wrong oauth signature because the path used in calculation is is not relative to the host but the absolute path.

**Comment by pinxue** [comment]
confirmed this temporary solution is fine, issue in last comment is caused by some other mistake.

**Comment by mattt** [comment]
@pinxue No need to override the implementation—you can simply pass the whole URL as the path argument. This is all by design.
