### ISSUE TITLE
No visibile interface error.

### ISSUE THREAD

**Issue by ignazioc** [AFNetworking/AFOAuth1Client#54]
/AFOAuth1Client/Twitter iOS Example Client/Twitter iOS Example Client/AppDelegate.m:41:6: No visible @interface for 'AFOAuth1Client' declares the selector 'authorizeUsingOAuthWithRequestTokenPath:userAuthorizationPath:callbackURL:accessTokenPath:accessMethod:success:failure:'

The name of the methods was changed in 
'authorizeUsingOAuthWithRequestTokenPath:userAuthorizationPath:callbackURL:accessTokenPath:accessMethod:_scope:_success:failure:

**Comment by mattt** [comment]
Fixed by #50.
