### ISSUE TITLE
ForegroundObserver isn't removed 

### ISSUE THREAD

**Issue by seivan** [AFNetworking/AFOAuth1Client#58]
I remember this PR from @eriksundin https://github.com/AFNetworking/AFOAuth1Client/commit/aa789cec616ec9b9d448643ab3d7054d33200f5a

that would take care of it.
It seems slightly altered now in 2.0, but from what I can tell, observers aren't being removed at all. 

Here's a sample app
https://github.com/seivan/SHOmniAuthLinkedIn

Steps to reproduce

1) Clone master https://github.com/seivan/SHOmniAuthLinkedIn

2) Run sample

3) Tap Add account on UIActionSheet button

4) Tap Cancel on Linkedin auth

5) Repeat 3) and 4)

You'd see three "null" messages in the console, you should only see two.

**Comment by mattt** [comment]
Fixed by #59. Thanks again!
