### ISSUE TITLE
Both iOS and Mac OS X Twitter example fail in the OAuth process!

### ISSUE THREAD

**Issue by altimac** [AFNetworking/AFOAuth1Client#7]
Twitter returns : " Failure: Failed to validate oauth signature and token"

I'm trying to use OAuth on another webservice that Twitter and get the same error....

So basically, the OAuth mechanism of AFNetworking does not work as expected :(

**Comment by altimac** [comment]
Forgot to add that of course the joergsimon branch works as expected!
So something failed in your merging. Please try the Twitter app (only the iOS twitter app example compiles on joergsimon's branch... the one for Mac OS X requires minor tricks though)

**Comment by mattt** [comment]
AFOAuth1Client 0.1.0 includes fully-operational Twitter examples on iOS and Mac.
