### ISSUE TITLE
0.2.1 Podspec needs to be updated to not pull AFNetworking 2.0.0+

### ISSUE THREAD

**Issue by umjames** [AFNetworking/AFOAuth1Client#73]
AFNetworking 2.0 causes conflicts with projects with platform targets < iOS 7 and with other CocoaPods that use earlier versions of AFNetworking.

If the dependency on AFNetworking was more restrictive than "> 1.0", like "~> 1.0", that could fix the problem.

**Comment by seivan** [comment]
I agree.
It's pretty messed up that a bump from AFOAuth1Client  `0.2.0` to `0.2.1` there is a whole new dependency that will make a ton of code freak out. 

May I suggest that you keep `~> 0.2.0`  - that means from `0.2.0` to `0.2.9` attached to AFNetworking `~> 1.3.1`

Though I understand that pre 1 things will break, there was a more graceful way of going at it. 

I am not sure how to do a pull request to a tag, but can I suggest changing the tag 0.2.0 to using this in its podspec.

``` ruby
  s.dependency 'AFNetworking', '~> 1.3.0'
```

And changing the 0.2.1 tag to 0.3.0 instead.

**Comment by tomburns** [comment]
Submitted a pull request to set the AFN dependency to ~> 1.3.1, we'll see if it's accepted!

**Comment by orta** [comment]
As an aside, if you do  `pod "AFNetworking", "~> 1"` before AFOAuth CocoaPods should resolve the dependency to a 1.x version.

**Comment by seivan** [comment]
Yeah, for now that's what making it build, but should not be a necessity and I hope we can resolve this. 

@tomburns  https://github.com/AFNetworking/AFOAuth1Client/pull/75

**Comment by seivan** [comment]
Where are we on this?

**Comment by mattt** [comment]
Fixed by #75, and resolved in the main specs repo. Sorry all for the inconvenience.
