### ISSUE TITLE
AFOAuth1Client won't build against 2.0.0-rc1

### ISSUE THREAD

**Issue by tomburns** [AFNetworking/AFOAuth1Client#74]
This client doesn't build against AFNetworking 2.0.0-rc1, and doesn't specify 1.3 in the podfile, so new projects using it don't build out of the box without manually specifiying AFNetworking ~> 1.3. Should we just stick with manually specifying both pods in our workspace Podfiles for now, or get a patch in?

**Comment by mattt** [comment]
Fixed by #75. Thanks again, @tomburns.
