### ISSUE TITLE
Compatibility with AFNetworking 2.0.0

### ISSUE THREAD

**Issue by piotrtobolski** [AFNetworking/AFOAuth1Client#86]
It would be quite useful if this library would get upgraded to be comptaible with AFNetworking 2.0.0

**Comment by TheBearF8** [comment]
I would agree, that would be nice.
I would also add a fuller example on using AFOAuth1Client
Beyond getting the Access Token which the Twitter example shows only.

**Comment by jamieforrest** [comment]
+1 on v2 compatibility

**Comment by bdbergeron** [comment]
Since the architecture has changed quite a bit for AFNetworking 2.0, it's not exactly a simple update. I've made my own 2.0-compatible replacement that I'm using in a few projects. If you want to check it out, it's available at https://github.com/bdbergeron/BDBOAuth1Manager.

**Comment by iceydee** [comment]
Thanks @bdbergeron!

**Comment by bdbergeron** [comment]
Not a problem. It's very much a work-in-progress even though I tagged it as a 1.0 level release. If any of you guys have suggestions or find bugs, @mattt included, please let me know.

**Comment by tomburns** [comment]
@bdbergeron any reason this couldn't be submitted as a pull request here, replacing the 1.3.x subclasses? I've been developing against it without issue so far.

**Comment by lmcd** [comment]
+1

**Comment by ishaq** [comment]
+1

for now I'm going with @bdbergeron's replacement.

**Comment by krzyzanowskim** [comment]
+1

**Comment by pratikvelani** [comment]
+1

**Comment by ngoohebi** [comment]
+1

**Comment by iwasrobbed** [comment]
:+1:

**Comment by digvan** [comment]
+1

**Comment by joelchen** [comment]
I have ported AFOAuth1Client to support the latest AFNetworking 2. Have a go at: https://github.com/joelchen/AFOAuth1Client

**Comment by wouterds** [comment]
Great! Why isn't this merged yet?

**Comment by piotrzbyszynski** [comment]
Bumping, any news on that?

**Comment by wouterds** [comment]
Nope

**Comment by mengdun** [comment]
+1

**Comment by mattt** [comment]
To respond to the OP's question, OAuth 1 is deprecated in favor of OAuth 2, with few modern web services using it today. As such, it is not a high priority for the AFNetworking project.

Today, AFOAuth1Client has been tagged at 1.0.0, with all outstanding PRs and issues resolved. It targets AFNetworking 1.3.x.

@bdbergeron was correct in noting that a port to AFNetworking 2.0 is non-trivial, as the new request serializer APIs are incompatible with how AFOAuth1Client was originally implemented. BDBOAuth1Manager does a good job with porting to AFN 2, and I would be very interested in back-porting those changes if a @bdbergeron is interested.

#103 proposes merging @joelchen's fork, which although technically compatible with the AFN 2 APIs, does so in a way that does not take advantage of new functionality.

**Comment by bdbergeron** [comment]
@mattt Although it may be more of a hassle than it's worth, I'd be willing to rename BDBOAuth1Manager to AFOAuth1Manager and transfer the repository to you, or I could push it as a new branch to this repo and rename it (similar to what you did with AFOAuth2Client -> AFOAuth2Manager). Let me know what you think.
