### ISSUE TITLE
Does not work with current versions of AFNetworking

### ISSUE THREAD

**Issue by iamcam** [AFNetworking/AFOAuth1Client#9]
It doesn't seem AFOAuth1Client will work with the current version of AFNetworking - AFHTTPClient.m is duplicated between the two, but with different functionality.

**Comment by rdougan** [comment]
I've submitted a pull request (#10) to resolve this.

**Comment by iamcam** [comment]
Thanks! Hopefully it'll go through soon. I may just pull from your branch in the meantime.

**Comment by mattt** [comment]
Working with 0.1.0. Cheers!

**Comment by iamcam** [comment]
Thanks!
