### ISSUE TITLE
isExpired check

### ISSUE THREAD

**Issue by dmishe** [AFNetworking/AFOAuth1Client#90]
Right now token expiration is checked this way:

```
 [self.expiration compare:[NSDate date]] == NSOrderedDescending;
```

Which, if I'm not mistaken, means (expiration > now), while it should be (expiration < now) because we want to test if token expires at a date in the future?

**Comment by mattt** [comment]
Yep. Looks like it was originally backwards with its addition in 2dca4ee9. 140f474 makes that change. Thanks for pointing this out, @dmishe.
