### ISSUE TITLE
0.3.2 Breaks and CocoaPods Issue

### ISSUE THREAD

**Issue by joeldrotleff** [AFNetworking/AFOAuth1Client#97]
So I just noticed that upgrading from 0.3.2 from 0.3.1 breaks for me. Not sure exactly why yet but reverting back to 0.3.1 fixed the issue (I am using AFOAuth1Client to connect to the Yelp API but without any user authentication). BTW great library.

Anyway for now I was planning to fix this by staying on 0.3.1, but what is odd is that CocoaPods will still install the latest version. I updated my Podfile like this:

`pod 'AFOAuth1Client', '~> 0.3.1'`

But when I run pod update it still does this: 

`Installing AFOAuth1Client (0.3.2)`

It seems like the Podspec for 0.3.1 is there in the repo and everything (https://github.com/CocoaPods/Specs/tree/master/AFOAuth1Client) so I'm not sure what the issue is. Is this a CocoaPods issue you think? I tried running `pod repo update` too and it still installs 0.3.2.

**Comment by joeldrotleff** [comment]
Regarding the CocoaPods issue, that was my mistake: https://github.com/CocoaPods/CocoaPods/issues/1550

**Comment by toco** [comment]
Could be the issue fixed in 1bcf1463e2f29b776e9fa4b1f94839c9e0dd075e, #93  and #95.
